// Dreamize API Configuration

export const BASE_URL = 'http://localhost:5000';

export const API_ENDPOINTS = {
  AUTH_REGISTER: '/api/auth/register',
  AUTH_REGISTER_STUDENT: '/api/auth/register/student',
  AUTH_REGISTER_TRAINER: '/api/auth/register/trainer',
  AUTH_LOGIN: '/api/auth/login',
  AUTH_LOGOUT: '/api/auth/logout',
  AUTH_SEND_OTP: '/api/auth/send-otp',
  AUTH_VERIFY_OTP: '/api/auth/verify-otp',
  AUTH_RESEND_OTP: '/api/auth/resend-otp',
  AUTH_FORGOT_PASSWORD: '/api/auth/forgot-password',
  AUTH_RESET_PASSWORD: '/api/auth/reset-password',
  AUTH_APPROVE_TRAINER: (id: string) => `/api/auth/trainers/${id}/approve`,
  AUTH_REJECT_TRAINER: (id: string) => `/api/auth/trainers/${id}/reject`,
  AUTH_ONBOARDING_CHECKLIST: '/api/auth/onboarding-checklist',
  USERS_ME: '/api/users/me',
  USERS: '/api/users',
  USERS_TRAINERS: '/api/users/trainers',
  USERS_STUDENTS: '/api/users/students',
  USER_STATUS: (id: string) => `/api/users/${id}/status`,
  USER_PROFILE: '/api/users/profile',
  USER_BY_ID: (id: string) => `/api/users/${id}`,
  BOOKING: '/api/bookings',
  BOOKING_TRAINER: '/api/bookings/trainer',
  BOOKING_STUDENT: '/api/bookings/student',
  BOOKING_APPROVE:(id:string)=>`/api/bookings/${id}/approve`,
  BOOKING_REJECT:(id:string)=>`/api/bookings/${id}/reject`,
  ROADMAPS: '/api/roadmaps',
  ROADMAP_BY_ID: (id: string) => `/api/roadmaps/${id}`,
  ROADMAP_SUBMIT: (id: string) => `/api/roadmaps/${id}/submit`,
  ROADMAP_APPROVE: (id: string) => `/api/roadmaps/${id}/approve`,
  CHAT_CONTACTS: '/api/chat/contacts',
  CHAT_MESSAGES: (contactId: string) => `/api/chat/messages/${contactId}`,
  PAYMENT_ORIANTATION: '/api/payments/orientation',
  PAYMENT_SUBSCRIPTION: '/api/payments/subscription',
  PAYMENT_CONFIRM: (id: string) => `/api/payments/${id}/confirm`,
  WALLET_ME: '/api/wallet/me',
  WALLET: '/api/wallet',
  STATS_ME: '/api/stats/me',
  NOTIFICATIONS: '/api/notifications',
  NOTIFICATION_BY_ID: (id: string) => `/api/notifications/${id}`,
  SYSTEM: '/api/system',
  TRAINERS_PENDING: '/api/trainers/pending',
  ADMIN_ANALYTICS: '/api/admin/analytics',
  ADMIN_FEEDBACK: '/api/admin/feedback',
  ADMIN_FEEDBACK_BY_ID: (id: string) => `/api/admin/feedback/${id}`,
  ADMIN_FEEDBACK_RESPONSE: (id: string) => `/api/admin/feedback/${id}/response`,
  FILES: {
    UPLOAD_AVATAR: '/api/files/avatar',
    UPLOAD_MESSAGE: '/api/files/message',
    UPLOAD_GENERIC: '/api/files/upload',
  },
};

export const SOCKET_EVENTS = {
  SEND_MESSAGE: 'send_message',
  MESSAGE_RECEIVED: 'message_received',
  NEW_NOTIFICATION: 'new_notification',
};
